apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "thuy-suon1"
  annotations:
    backstage.io/managed-by: scaffolder
    github.com/project-slug: sotatek-cloudteam/backsatge-1
    backstage.io/techdocs-ref: dir:.
spec:
  type: database
  owner: sotatek-dev-team
  lifecycle: experimental
